### ISSUE TITLE
Retraining with image size of 500x500

### ISSUE THREAD

**Issue by xjoshramos** [BichenWuUCB/squeezeDet#15]
When retraining with my own data set of size 500x500 I get the following error

ValueError: Cannot reshape a tensor with 466560 elements to shape [20,8100,2] (324000 elements) for 'interpret_output/pred_class_probs' (op: 'Reshape') with input shapes: [233280,2], [3].

What is the best way to modify the net and anchors?

 H, W, B = 22, 76, 9

**Comment by BichenWuUCB** [comment]
@xjoshramos The H and W should be approximately 1/16 of the input image size. However, due to integer rounding caused by padding/striding/down-sampling strategy, the exact number could be a bit different. Given input image size of 500x500, I would suggest starting with 32x32 and go through a few iterations of trial-and-error. 

B is just the number of anchors for each grid center, so it really depends on how many objects can be inside one image, the range of object size, etc.

**Comment by xjoshramos** [comment]
Thank you!

**Comment by xjoshramos** [comment]
My training data is not all the same size. When training, does the the resizing affect my bounding box ground truth? Is the ground truth change according to the resize or do I need to handle that on my end?

**Comment by BichenWuUCB** [comment]
@xjoshramos If you look at this line: https://github.com/BichenWuUCB/squeezeDet/blob/master/src/dataset/imdb.py#L189 You will see that bounding boxes are also scaled accordingly together with the image.
