### ISSUE TITLE
How to run on a mp4 video?

### ISSUE THREAD

**Issue by cedricve** [BichenWuUCB/squeezeDet#19]
Awesome contribution! I've looked in the demo script, and saw there is support for processing videos? However I tried it, but didn't succeeded in running it properly.

Any tips or howto, I get following error. Tried to install gtk2.0 seperately.

    cv2.destroyAllWindows()
    cv2.error: /io/opencv/modules/highgui/src/window.cpp:577: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvDestroyAllWindows

**Comment by cedricve** [comment]
Ok looks like video related functionality and GTK is not supported.

- video related functionality is not supported (not compiled with FFmpeg)
- for example cv.imshow() will not work (not compiled with GTK+ 2.x or Carbon support)

https://pypi.python.org/pypi/opencv-python

**Comment by cedricve** [comment]
ended up with compiling opencv from source and using the .so library directly.

**Comment by BichenWuUCB** [comment]
@cedricve Thanks for your interest. As a matter of fact, though SqueezeDet's speed definitely satisfies normal video's frame rate, but since it takes each frame as an independent input, in our previous experiments, we observed some discontinuity in prediction results between neighboring frames. We are currently working on improving SqueezeDet's performance on videos. So, stay tuned!

**Comment by cedricve** [comment]
@BichenWuUCB cool, I'll use your classifier in the @kerberos-io project (www.kerberos.io). If you need some data, let me know..

**Comment by acmaheri** [comment]
@BichenWuUCB are you already done on improving SqueezeDet's performance on videos?
