### ISSUE TITLE
IOU threshold

### ISSUE THREAD

**Issue by ByeonghakYim** [BichenWuUCB/squeezeDet#25]
Hi, 

I wonder if you use IOU threshold for box matching.

If you do, can you explain me what criterion to decide the anchor size?

Thanks in advance.
Byeonghak

**Comment by AndreaPisoni** [comment]
You can find the answers to all go your questions in the various config.py
files

**Comment by ByeonghakYim** [comment]
@AndreaPisoni Thanks, I've just checked and find that the set_anchors gives me the anchor box information.
But still can not find IOU threshold

**Comment by AndreaPisoni** [comment]
NMS_tresh on the config should be the IOU threshold for the non max
suppression algorithm

**Comment by ByeonghakYim** [comment]
@AndreaPisoni Most of detection algorithm has IOU threshold to assign positive and negative during the training. In the paper they said they choose the largest IOU anchor as positive, but in this way IOU with 0.01 also could be positive. They set the largest anchor as 366 x 174, but what if the object size is 700 x 700. Just I think, not definitely, that this cause the downside on the localization. How do you think of this? I would like to know your opinion.

**Comment by BichenWuUCB** [comment]
@ByeonghakYim Sorry for the delay to answer your question. Let me make sure if I understand your question correctly. You are wondering how we assign a ground truth bounding box to a reference anchor during training, is that right? Essentially, we assign the ground truth bbox to the anchor that has the largest IOU with it. It is possible that for extremely large or small objects, even the best IOU is very small. But that's just the candidate -- we also will compute bbox deltas to transform reference anchor to match the gt-bbox. 

In order to make our pre-selected anchor shapes to best match with the bbox distribution, we used a trick proposed in our previous [paper](https://arxiv.org/abs/1606.01561).

Does it make sense?

**Comment by ByeonghakYim** [comment]
@BichenWuUCB Yes, thanks so much. I think that anchor selection is the most important issue for performance, so I'm trying to find the best anchor box set without sacrificing processing time.
Thanks again
