### ISSUE TITLE
SqueezeDet is SSD on one layer

### ISSUE THREAD

**Issue by ymshao** [BichenWuUCB/squeezeDet#42]
Recently, I compared the detection pipeline of SqueezeDet and Single Shot Detection(By Wei Liu https://arxiv.org/abs/1512.02325). I found that squeezeDet is equal to the  SSD only applied on one feature layer, basically. There are some minor difference except this but really I found nothing more.

@BichenWuUCB What is your opinion? Can you spot some more difference? Thank you.

**Comment by BichenWuUCB** [comment]
@ymshao Thanks for your question.

Since SqueezeDet paper and code repository were released, we received several questions about comparing SqueezeDet with SSD, YOLO, etc. I'd like to take this chance to provide a response to these questions and share some thoughts.

The short answer is, yes, they are similar.

And in case someone is interested in a longer answer:

Our work was initially inspired by YOLO -- we used a one-stage detection pipeline to ensure fast inference speed. And to reduce parameters in fully connected layers, we used a convolutional layer as output for both region proposal and classification.  By the time the work is done, we thought that this was a novel idea. But later, we saw SSD from ECCV and we realized that SDD used an idea similar to ConvDet and it's been published on arxiv much earlier. We respect the originality of SDD using convolution as detection output layer. For a heated research topic like object detection, low hang fruits are usually picked much earlier than one would expect. 

But here is a more important point. The trend of research in object detection has been primarily focusing on pushing the state-of-the-art accuracy higher and higher. Meanwhile, however, problems such as inference speed, energy efficiency, model size, etc. are not adequately addressed. These are critical problems if we want NN models to get out of computer vision lab's workstation GPUs and be deployed on portable devices such as autonomous vehicles, mobile phones, etc.

So, the motivation for us to build SqueezeDet is to design a model deployable on embedded devices. All our design decisions are focusing on how to make it faster, how to reduce model parameters, how to reduce memory footprint, how to reduce energy consumption while keeping the same level of or even better accuracy. We are happy that after integrating many efficient design ingredients (SqueezeNet, one-stage detection, ConvDet, etc.), SqueezeDet achieved significant progress in all above aspects. Within less than half a year, SqueezeDet has been adopted by a lot of mobile apps, embedded vision processors, etc. That's what we are really happy to see.

**Comment by ymshao** [comment]
@BichenWuUCB  Thank you for such a comprehensive explanation, it really help a lot. You are right object detection is a so hot research subject that usually people are really testing and do experiments on very similar ideas. But only the one who can obtained the best accuracy (or release the code and paper earliest) get credit. The point is to make it work. And your code is not only work but very elegant, and I reproduced similar results as stated in the paper.  

I believe the researchers in this area will pay more attention on the speed, energy cost, model size in addition to accuracy. And you work is really a very good start.

Thank you for your reply again.
