### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by chenjiapen12** [BichenWuUCB/squeezeDet#44]
Hello, I know the speed of your  squeezeDet model is 57.2fps. But in my computer, reading one image using Opencv needs 0.025s. So I want to know if you include this time when you calculate speed? Thank you
@BichenWuUCB

**Comment by BichenWuUCB** [comment]
@chenjiapen12 Thanks for your question. 

The image loading time is not counted since one can hide the image loading latency by using multiple threads caching the images to GPU memory while running the inference simultaneously. See [here](https://www.tensorflow.org/programmers_guide/threading_and_queues) if you plan to implement this in Tensorflow. 

Bichen

**Comment by chenjiapen12** [comment]
Thank you very much
