### ISSUE TITLE
Issues extracting a frozen graph from the trained checkpoints. ( input and output nodes unclear )

### ISSUE THREAD

**Issue by amanmeetgarg** [BichenWuUCB/squeezeDet#94]
Hi All,
 I used the training and evaluation codes in the repo. Now i want to use the trained checkpoint data ( weights, meta, index ) files to freeze the graph and use it elsewhere.

I perform the following : 

path_to_ckpt_data : is the directory with the checkpoint files ( in the repo /tmp/bichen/*model/train

sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
saver = tf.train.import_meta_graph(path_to_ckpt_meta)
saver.restore(sess, path_to_ckpt_data)
tf.train.write_graph(sess.graph.as_graph_def(), rootdir, "model_ckpt_355000_graph.pb")

This code above writes the graph_def file.

Then I use the freeze_graph.py in the tensorflow tools to find the freezegraph to then perform benchmarking and test the trained model performance. 

However, the system is constantly giving me no input found error.

My question is, in the training setup as per the repository, what are the input nodes and the output nodes to perform model freeze as per tensorflow methodology ?

Any help is much appreciated :-) @BichenWuUCB

**Comment by BichenWuUCB** [comment]
Thanks for your question. I used freeze_graph some time ago and here are some suggestions:

The inputs to the model are defined [here](https://github.com/BichenWuUCB/squeezeDet/blob/master/src/nn_skeleton.py#L121).

In order to use freeze_graph, you may need to strip off some place holder definitions [here](https://github.com/BichenWuUCB/squeezeDet/blob/master/src/nn_skeleton.py#L81) and some input nodes that are only used in training. E.g., labels, etc. 

The output node that you need for inference includes [bbox](https://github.com/BichenWuUCB/squeezeDet/blob/master/src/nn_skeleton.py#L235), [prob](https://github.com/BichenWuUCB/squeezeDet/blob/master/src/nn_skeleton.py#L282), [cls_id](https://github.com/BichenWuUCB/squeezeDet/blob/master/src/nn_skeleton.py#L283). 

When using freeze_graph, you may need to use the variable name (an attribute of a TF tensor) to denote input and output variables. 

Hope it helps,
Bichen

**Comment by amanmeetgarg** [comment]
Thanks for the detailed message.. I will get working on these..

Best
Aman

**Comment by amanmeetgarg** [comment]
@BichenWuUCB I have been on it all day and used optimize_for_inference.py from tensorflow.

However, I am getting a strange behaviour , when I do freeze_graph with the graph_def and checkpoint file,  The output model has no input node.  .. Thus rendering the model unusable. 

Is there a specific transformation that I am missing in my call to freeze_graph .. did you do some specific transformation ?

Any code example on how you converted the model for the freeze_graph would be greatly helpful.

Thanks for all your help

Best
Aman

**Comment by BichenWuUCB** [comment]
Can you give exact error message? Since I'm not sure what it means by the model has no input node.

**Comment by amanmeetgarg** [comment]
@BichenWuUCB  @alvinwan  [frozen_graph_layers_V2.txt](https://github.com/BichenWuUCB/squeezeDet/files/1813555/frozen_graph_layers_V2.txt)

the file frozen_layers_V2.txt has the print of all the nodes in the frozen model from freeze_graph.py

it shows that the frozen model does not have an image_input node

after that I run the optimize_for_inference.

**COMMAND** bazel-bin/tensorflow/python/tools/optimize_for_inference --input=/tmp/logs/squeezeDet_NewDataset_test01_March02/train/frozen_sqdt_ckpt_355000.pb --output=/tmp/logs/squeezeDet_NewDataset_test01_March02/train/frozen_sqdt_ckpt_355000_optimized.pb --frozen_graph=True --input_names=image_input --output_names=bbox/trimming/bbox,probability/score,probability/class_idx

**OUTPUT** ->
Traceback (most recent call last):
  File "/home/ubuntu/target_TFInstall/tensorflow/bazel-bin/tensorflow/python/tools/optimize_for_inference.runfiles/org_tensorflow/tensorflow/python/tools/optimize_for_inference.py", line 146, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/ubuntu/target_TFInstall/tensorflow/bazel-bin/tensorflow/python/tools/optimize_for_inference.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/target_TFInstall/tensorflow/bazel-bin/tensorflow/python/tools/optimize_for_inference.runfiles/org_tensorflow/tensorflow/python/tools/optimize_for_inference.py", line 90, in main
    FLAGS.output_names.split(","), FLAGS.placeholder_type_enum)
  File "/home/ubuntu/target_TFInstall/tensorflow/bazel-bin/tensorflow/python/tools/optimize_for_inference.runfiles/org_tensorflow/tensorflow/python/tools/optimize_for_inference_lib.py", line 109, in optimize_for_inference
    placeholder_type_enum)
  File "/home/ubuntu/target_TFInstall/tensorflow/bazel-bin/tensorflow/python/tools/optimize_for_inference.runfiles/org_tensorflow/tensorflow/python/tools/strip_unused_lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_found)
**KeyError: "The following input nodes were not found: set(['image_input'])\n"**



So the issue suggests that the frozen model generated does not have image_input nodes .. from your previous response it hints towards a possible issue with the placeholder nodes being placed in the fifo_que and need to be removed. 

How were you able to generate the frozen model for inference.

Thank you for your help
Aman

**Comment by BichenWuUCB** [comment]
I think it's probably because the input node (TF variable) is not named "image_input" in the TF computation graph. It can be a bit confusing that the [TF variable name](https://www.tensorflow.org/versions/master/api_docs/python/tf/Variable) is not the same as python variable name. So, you need to find the right  __TF variable name__ for the [input tensor](https://github.com/BichenWuUCB/squeezeDet/blob/master/src/nn_skeleton.py#L121).

**Comment by amanmeetgarg** [comment]
@BichenWuUCB  thanks for your response .. 
was there a specific transformation that you had to run .. I am using the exact training code as per your repo.
Any code example snippet that you can share ?

Thanks
Aman.

**Comment by BourbonCreams** [comment]
Hi @amanmeetgarg,

Did you eventually manage to get it to work?

Thanks

**Comment by amanmeetgarg** [comment]
@BourbonCreams No solution, tried my level best .. implemented my own.

**Comment by pribadihcr** [comment]
@amanmeetgarg,

have you your own implementation?

**Comment by amanmeetgarg** [comment]
@pribadihcr I implemented my own version using the trained model from the Repo code.

All the best.
